version: '3'
services:  
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "80:8080"
    volumes:
      - ../src:/src
      - ./nginx/playground.conf:/etc/nginx/conf.d/playground.conf
      - "run:/run"
    depends_on:
      - fpm
  fpm:
    container_name: fpm
    image: php:8.1-fpm-alpine
    volumes:
      - ../src:/src
      - "./fpm/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf"
      - "run:/run"
    depends_on:
      - composer
  composer:
    container_name: composer
    image: composer:2.1
    volumes:
      - ../src:/src
    working_dir: /src
    command: install
volumes:
  run: