version: '3'
services:

    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - "80:8080"
        volumes:
            - ../src:/src
            - ./nginx/playground.conf:/etc/nginx/conf.d/playground.conf
            - "run:/run"
        depends_on:
            - fpm

    fpm:
        container_name: fpm
        image: php:8.1-fpm-alpine
        volumes:
            - ../src:/src
            - "./fpm/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf"
            - "run:/run"
        depends_on:
            - composer
            - database

    composer:
        container_name: composer
        image: composer:2.1
        volumes:
            - ../src:/src
        working_dir: /src
        command: install

    database:
        container_name: database
        image: postgres:14.1-alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: 'currency_exchange'
            POSTGRES_PASSWORD: 'password'
            POSTGRES_USER: 'symfony'
            PGDATA: '/data'
        volumes:
            - data:/data

# @todo Needs some work to make it running
#    cli:
#        container_name: cli
#        image: php:8.1-cli-alpine
#        volumes:
#            - ../src:/src
#        depends_on:
#            - composer
#            - database
#        command: >
#            sh -c "set -ex apk --no-cache add postgresql-dev &&
#                   /usr/local/bin/docker-php-ext-install pdo pdo_pgsql &&
#                   php /src/bin/console doctrine:fixtures:load"

volumes:
    run:
    data:
    