version: '3'
services:

    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - "80:8080"
        volumes:
            - ../src:/src
            - ./nginx/playground.conf:/etc/nginx/conf.d/playground.conf
            - "run:/run"
        depends_on:
            - fpm

    fpm:
        container_name: fpm
        build: ./fpm/
        volumes:
            - ../src:/src
            - "./fpm/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf"
            - "run:/run"
        depends_on:
            - composer
            - database

    composer:
        container_name: composer
        image: composer:2.1
        volumes:
            - ../src:/src
        working_dir: /src
        command: install

#    database:
#        container_name: database
#        image: postgres:14.1-alpine
#        ports:
#            - "5432:5432"
#        environment:
#            POSTGRES_DB: 'currency_exchange'
#            POSTGRES_PASSWORD: 'password'
#            POSTGRES_USER: 'symfony'
#            PGDATA: '/data'
#        volumes:
#            - data:/data

    database:
        container_name: database
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: 'currency_exchange'
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_USER: 'symfony'

    cli:
        container_name: cli
        build: ./fpm/
        volumes:
            - ../src:/src
        depends_on:
            - composer
            - database
        command: >
            sh -c "php /src/bin/console doctrine:schema:update --complete --force && 
            php /src/bin/console doctrine:fixtures:load"

volumes:
    run:
    data:
    